version: '3'

services:
  ml_service:
    build: .
    ports:
      - "8000:80"
    volumes:
      - './notebooks:/app/notebooks'
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]

  jupyter:
    image: jupyter/scipy-notebook
    ports:
      - "8888:8888"
    volumes:
      - './notebooks:/home/jovyan/work'
    user: root