apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: inference
  name: inference
spec:
  ports:
    - name: "8602"
      port: 8602
      targetPort: 8602
  selector:
    io.kompose.service: inference
