version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  api:
    build: .
    container_name: rag-api
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - qdrant
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data

  frontend:
    build: 
      context: ./front
      dockerfile: Dockerfile
    container_name: rag-frontend
    ports:
      - "8080:80"
    depends_on:
      - api

  sqliteweb:
    image: coleifer/sqlite-web:latest
    container_name: sqliteweb
    ports:
      - "8082:8080"
    volumes:
      - ./data:/data:ro
    command: ["sqlite_web", "--host", "0.0.0.0", "/data/chat_history.db"]
    depends_on:
      - api


volumes:
  qdrant_data:
